### PR TITLE
Added voice integration using Alan AI Closes #22

### LINKED ISSUE #22: Add a voice assistant feature
Add a voice assistant which can interact and respond to the user's queries regarding the weather. For example, if you tell the name of the city, it will tell you the weather there. This will also make the website more accessible to everyone.

### PR DESCRIPTION
**Pull request by sumana2001**
In the screen recording given below, we have shown some of the features that the voice assistant will be able to do as of now. We have written the entire script in the Alan AI studio and imported it into our website using the SDK key. We have also added a toast message for users to know how to start interacting with the bot. When the bot is talking about the weather of a particular city, the map and location also changes to that city as shown in the video. More features like viewing weekly forecasts and all can be added to the voice recognition later when these features are added to the deployed website.

Closes #22

This video wasn't uploading here because of some error, so sharing a drive link
https://drive.google.com/file/d/1lrPQrVez2KUfqix7OMOo-eo2eCBuF3gY/view?usp=sharing

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@sumana2001 Please, fix conflict

**Comment by grace-omotoso** [comment]
@sumana2001 Please, fix merge conflicts

**Comment by sumana2001** [comment]
@grace-omotoso Fixed the merge conflicts. Please review

**Comment by AdarshNaidu** [comment]
The feature works great and the functionalities are well implemented.

Can you also add setup instructions in the README, so when this is merged in main, rest of us can refer it to make it work locally.
Some things to include:

- Where to get the api key from
- Name of api key
- Anything that needs to be done in AlanAI website.

**Comment by sumana2001** [comment]
Hey @AdarshNaidu, since I don't want the API key to be public and the API key is connected to the script, should I attach the entire script in the readme in a drive link or something so that people can add that script in Alan studio and get their API key?

**Comment by sumana2001** [comment]
Hey @AdarshNaidu 
I have added the documentation, please have a look.

**Review by AdarshNaidu — APPROVED** [review]
LGTM!

**Review by grace-omotoso — APPROVED** [review]

**Comment by grace-omotoso** [comment]
> The feature works great and the functionalities are well implemented.
> 
> Can you also add setup instructions in the README, so when this is merged in main, rest of us can refer it to make it work locally. Some things to include:
> 
> * Where to get the api key from
> * Name of api key
> * Anything that needs to be done in AlanAI website.

Thanks Adarsh for spotting that this features must be documented properly.

**Pull request merged**
