### PR TITLE
Fixed navigation bar responsiveness

### LINKED ISSUE #56: Make navbar responsive
Make the navbar responsive for all screen sizes. Probably use a hamburger in mobile view
Screenshot 2021-11-24 at 3 45 19 PM

### PR DESCRIPTION
**Pull request by OjusWiZard**
Used react-bootstrap to add a responsive navbar. Also, added a toggle button as a hamburger menu. Closes #56

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@PriyaBihani It appears there is a regression with the daily forecast cards. Cards are overflowing
daily forecast cards

**Review by grace-omotoso — CHANGES_REQUESTED** [review]
Please, fix the regressions with the daily cards forecast

**Comment by grace-omotoso** [comment]
@PriyaBihani Please, fix conflicts

**Comment by OjusWiZard** [comment]
@grace-omotoso I've fixed the conflicts now. PTAL

**Comment by grace-omotoso** [comment]
@PriyaBihani Please, fix conflicts

**Comment by OjusWiZard** [comment]
@grace-omotoso, conflicts fixed.

**Review by grace-omotoso — APPROVED** [review]

**Pull request merged**
