### PR TITLE
added background themes

### LINKED ISSUE #2: Change the colour scheme based on temperature / weather type
Change the websites appearance to match the weather conditions. The Apple Weather app has some cool examples in iOS 15, check them out [here](https://9to5mac.com/2021/09/24/ios-15-weather-app-hands-on/).

### PR DESCRIPTION
**Pull request by neha-93**
this PR closes #2 #28

### CODE REVIEW

**Comment by GrayFlash** [comment]
@neha-93 in the preview I am not able to edit the name of city, can you check that once.

**Comment by neha-93** [comment]
@GrayFlash I fixed the issue, can you check again

**Comment by iamwyh2019** [comment]
Added the °C/°F toggle. Resolved conflicts. Ready for merging!

**Comment by grace-omotoso** [comment]
@iamwyh2019 @neha-93  not a good practice to implement two issues in one PR. I will merge this, just wanted to let you know it is important to separate concerns. This is a major issue, thanks to the team for getting this done

**Review by akshitadixit — COMMENTED** [review]
Looks good to me, except this one thing:

image

In the mobile view, the C/F toggle button seems too large. We could create another issue for the same if @grace-omotoso wants, otherwise this should be a quick fix.

**Comment by grace-omotoso** [comment]
@neha-93 and co. Please, fix merge conflict and respond to Akshita's review

**Comment by iamwyh2019** [comment]
It's a bit hard to change the toggle size since the toggle size is hard-coded in the package (height 24px). However I can make the logo and navbar larger so that it matches better. Does that work?

image

**Comment by akshitadixit** [comment]
@iamwyh2019 this looks good too 👍👍

**Comment by iamwyh2019** [comment]
Sure. I will work on resolving conflicts.

**Comment by iamwyh2019** [comment]
Conflicts resolved. Please merge.

**Comment by grace-omotoso** [comment]
@neha-93 Apologies, please, resolve the conflict again. I will merge once that is done. Thanks

**Comment by iamwyh2019** [comment]
Our PR's a big update and its base is quite old so I'm worried that the mainstream's evolving too fast and making it virtually impossible to solve conflicts. Anyway, I will look at the conflicts tomorrow, and if things are messy, will try to redo our work on the newest mainstream.

**Comment by neha-93** [comment]
resolved all the conflicts, ready for merging.

**Review by grace-omotoso — APPROVED** [review]

**Pull request merged**
