### PR TITLE
Fixed loader spacing and displaying

### LINKED ISSUE #13: Add a loader instead of Text

### PR DESCRIPTION
**Pull request by OjusWiZard**
Closes #13

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@PriyaBihani Please, fix conflicts

**Comment by OjusWiZard** [comment]
@saikeshari PTAL

**Comment by grace-omotoso** [comment]
@PriyaBihani The loader is still in effect when the user types. The loader should only work when transitioning between pages and when refreshing or loading page. Please take a look at this. Thanks

**Comment by OjusWiZard** [comment]
@grace-omotoso Now it's showing the loader while the page is loading. But, haven't removed the loader when it's making the API call because it improves the UX, as the user gets the feedback that it's fetching the data from the API.

**Review by grace-omotoso — APPROVED** [review]

**Pull request merged**
