### PR TITLE
Helping the user bring the right things based on the weather closes #4

### LINKED ISSUE #4: Helping the user bring the right things based on the weather
- If it's raining, bring an umbrella
- If it's sunny, bring suncream
- If it's cold, bring a coat

### PR DESCRIPTION
**Pull request by PriyaBihani**
It will change according to weather type

image

### CODE REVIEW

**Comment by PriyaBihani** [comment]
@grace-omotoso please review

**Comment by saikeshari** [comment]
The same problem is happening here, deploy previews in netlify are built without environment variables.
Can we somehow include them in the netlify build? @grace-omotoso

**Comment by PriyaBihani** [comment]
@grace-omotoso please review

**Comment by saikeshari** [comment]
@PriyaBihani Please make the component responsive.
On small devices, it is overflowing

**Comment by PriyaBihani** [comment]
@saikeshari it's done.

**Review by saikeshari — APPROVED** [review]

**Review by grace-omotoso — APPROVED** [review]

**Pull request merged**
