### PR TITLE
Added the dynamic background theme.

### PR DESCRIPTION
**Pull request by neha-93**
Depending upon the climatic condition background theme changes.

### CODE REVIEW

**Comment by grace-omotoso** [comment]
Please, fix conflicts

**Comment by grace-omotoso** [comment]
@neha-93 Please, fix conflicts

**Comment by neha-93** [comment]
fixed the conflict, please check.

**Comment by grace-omotoso** [comment]
@neha-93 Please, fix conflicts

**Comment by grace-omotoso** [comment]
@neha-93 please, fix merge conflicts

**Comment by neha-93** [comment]
had a lot of conflicts that were difficult to resolve so copied the original project and added the file.

**Pull request closed without merging**
