### PR TITLE
Implement Bookmark Feature

### PR DESCRIPTION
**Pull request by Young-Einstein10**

### CODE REVIEW

**Review by saikeshari — COMMENTED** [review]
In the deploy preview, when I am clicking on Bookmarks in Navbar, it doesn't show anything on the page, just a blank white.
Please have a look.

**Comment by Shubh4m-B** [comment]
> In the deploy preview, when I am clicking on Bookmarks in Navbar, it doesn't show anything on the page, just a blank white. Please have a look.

Hey @saikeshari , I think that is happening because you might not have added any bookmarks. Can you please try adding some cities to your bookmarks and check again.

**Comment by Shubh4m-B** [comment]
> In the deploy preview, when I am clicking on Bookmarks in Navbar, it doesn't show anything on the page, just a blank white. Please have a look.

Hey @saikeshari , I think that is happening because you might not have added any bookmarks. Can you please try adding some cities to your bookmarks and check again.

**Comment by saikeshari** [comment]
Yes, when I add bookmarks, it is visible.
But it should display that no bookmarks added when it is empty instead of showing a blank white screen. Please do these changes.

**Comment by Young-Einstein10** [comment]
> Yes, when I add bookmarks, it is visible. But it should display that no bookmarks added when it is empty instead of showing a blank white screen. Please do these changes.

That's right...I'll make a fix for that now

**Review by grace-omotoso — APPROVED** [review]

**Pull request merged**
